# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/genad',
                'doc_host': 'https://iCalculated.github.io',
                'git_url': 'https://github.com/iCalculated/genad',
                'lib_path': 'genad'},
  'syms': {'genad.core': {'genad.core.foo': ('core.html#foo', 'genad/core.py')}}}
